# app/config/config.yml (Symfony without Flex)
# config/packages/firebase.yaml (Symfony with Flex)
kreait_firebase:
  projects:
    # You can access your firebase project with
    # $container->get('kreait_firebase.first')
    first:
      # Optional: If set to false, the service and its alias
      # can only be used via dependency injection
      public: true
      # Optional: If set to true, this project is used when
      # using Kreait\Firebase as a type hint for dependency injection
      default: false
      # Optional: Path to the projects Service Account credentials file
      # If omitted, the library will try to discover it.
      credentials: '%kernel.project_dir%/config/service_account_credentials.json'
      # You can find the database URI at
      # https://console.firebase.google.com/project/first/database/data
      database_uri: 'https://starter-kit-214419.firebaseio.com'
      # Optional: If set, you can access your project with
      # $container->get('firebase')
      alias: 'starter-kit-214419'
    second: # $container->get('kreait_firebase.second')
      database_uri: 'https://second.firebaseio.com'
    third: # $container->get('kreait_firebase.third')