security:

  encoders:
    FOS\UserBundle\Model\UserInterface: bcrypt

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: ROLE_ADMIN

  providers:
    oauth_user_provider:
      id: app.fos_user.oauth_provider

  firewalls:
    # Set the config on your firewall
    main:
      oauth:
        # Declare the OAuth Callback URLs for every resource owner
        # They will be added in the routing.yml file too later
        resource_owners:
          facebook: "/connect/check-facebook"
        ## Provide the original login path of your application (fosuserroute)
        ## and the failure route when the authentication fails.
        login_path:     /login
        failure_path:   /loginfailed
        # Inject a service that will be created in the step #6
        oauth_user_provider:
          service: app.fos_user.oauth_provider

    access_control:
      - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/admin/, role: ROLE_ADMIN }