version: '3'

services:
  nginx:
    build: 
      context: ./docker/nginx # this will use the latest version of 1.13.x
      dockerfile: nginx.Dockerfile
    ports:
      - '8080:80' # expose 80 on host and sent to 80 in container
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  web:
    image: httpd  # this will use httpd:latest
    volumes:
      - .:/usr/local/apache2/htdocs/
  php:
    build: 
      context: ./docker/php
      dockerfile: php.Dockerfile
    ports:
      - '80:80'
    volumes:
      - '.:/var/www/html'
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: starterkit
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: