version: '3'

services:
  nginx:
    build: 
      context: ./docker/nginx # this will use the latest version of 1.13.x
      dockerfile: nginx.Dockerfile
    # ports:
      # - '8080:80' # expose 80 on host and sent to 80 in container
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  web:
    image: httpd  # this will use httpd:latest
    volumes:
      - .:/usr/local/apache2/htdocs/
  php:
    build: 
      context: ./docker/php
      dockerfile: php.Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '.:/var/www/html'
    links:
      - mysql
      - phpmyadmin

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: sf4_phpmyadmin
  #   ports:
  #     - 9090:80
  #   depends_on:
  #      - mysql
  #   links:
  #      - mysql
  #   environment:
  #     - PMA_ARBITRARY=1

  mysql:
    build:
      context: ./docker/mySQL
      dockerfile: mySQL.Dockerfile
#    restart: always
    ports:
      - 3306:3306
#    entrypoint: /localdb-run.sh
    volumes:
#      - ./config/mysql:/etc/mysql/conf.d:ro
#      - ./docker/mySQL/docker-entrypoint.sh:/docker-entrypoint-initdb.d/docker-entrypoint.sh
      - ./data/mysql:/var/lib/mysql
#      - ./docker/mySQL/:/stack/localdb/
    environment:
      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: starterkit
#      MYSQL_USER: user
#      MYSQL_PASSWORD: pass
#    command: "/stack/localdb/localdb-run.sh"
#
#  phpmyadmin:
#    build:
#      context: docker/phpmyadmin
#      dockerfile: docker/phpmyadmin/phpmyadmin.Dockerfile
#    links:
#      - mysql:mysql
#    ports:
#      - 1234:80
#    environment:
#      PMA_USER : root
##      PMA_PASSWORD : root
#    environment:
#      - PMA_ARBITRARY=1
#

  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     container_name: sf4_phpmyadmin
     ports:
       - '9090:80'
     links:
        - mysql:mysql
     environment:
       PMA_PORT: 3306
#     environment:
#       - PMA_ARBITRARY=1
#      PMA_HOST : mysql
#      MYSQL_USERNAME: root
#      MYSQL_ROOT_PASSWORD: examplepass


# volumes:
#   data: