fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_lucky_number:
    path: /
    controller: App\Controller\LuckyController::number

api_login_check:
    path: /api/login_check